name = "portal"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://rrqbzanpgtxljdpcaakg.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJycWJ6YW5wZ3R4bGpkcGNhYWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0NzEwNTIsImV4cCI6MjA4MjA0NzA1Mn0.NL-HSV9r6yCKhCmahduwHB4IUjpk778i7vgxQYAJPoQ"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJycWJ6YW5wZ3R4bGpkcGNhYWtnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NjQ3MTA1MiwiZXhwIjoyMDgyMDQ3MDUyfQ.AsnGFrMTolJkvQ0tvBky2TSPFN1WqRXseYfFhCSIp4s"
AUTH0_SECRET = "1f795ca7c00b2d29542b363ef1f6ee4738d4168f1de1655933d063e56695a7a2"
AUTH0_ISSUER_BASE_URL = "dev-n5xojcaixa6wq0hy.us.auth0.com"
AUTH0_CLIENT_ID = "fy6wJWDmbIT3ZXMDHcsDBjYiDjY4FI6g"
AUTH0_CLIENT_SECRET = "31SXextgkzvUsG7k6HrMI4YfE_0KaDM3LKYqV2U9lY8hUcJQtlINi7uDdTj4H9wf"
PODIO_CLIENT_ID = "portal-23"
PODIO_CLIENT_SECRET = "8aG53YKbB2cSFyE2PeJoEke1AoGruQ8cGX7EgwR6fNSHzvNuyjZ219fCy7jf2VXw"
PODIO_TOKEN_CUSTOMERS = "f0c247995405ea24387b03da952e5578"
PODIO_TOKEN_DEVICES = "91485f634b76751231f9f81e22da067c"
PODIO_TOKEN_SERVICES = "b529f38ab2c9725fbce2446cf1546381"
PODIO_TOKEN_SERVICE_OR_SPARE_PART = "004971ac35fcfeec37ff927df41b939f"
PODIO_TOKEN_STORE = "bfdfb4ed18330afe388913586d23d147"
PODIO_TOKEN_GAMER = "1cca3da14b3c2772c0de87d0dce9ec92"
PODIO_TOKEN_ACQUIRED_DEVICES = "5cac7e5b078c9b07e52639b18b1a9d09"
PODIO_TOKEN_QUOTATIONS = "41c44a600ec33849ab8216357ccaf688"
PODIO_TOKEN_PLANS = "db12d8855fa3928a860a647666009857"
PODIO_TOKEN_INVOICES = "ce3724d6f219844032e540db9acf3a5b"
PODIO_TOKEN_APPOINTMENTS = "7ecfe00647b81ae6de1171a469a96f8b"
PODIO_TOKEN_TICKETS = "1067ea52df5aa054b8a2b7f2b4dca003"
PODIO_TOKEN_STUDENTS = "b17a172887bc4d7c33c2940771ec56e2"
PODIO_TOKEN_COURSES = "ce6cc0d966116f1725aa7297a906a249"
PODIO_TOKEN_CLASSES = "a58c51cfcefea0e565dab8158f2793bb"
PODIO_TOKEN_ENROLLMENTS = "aba98cb8f819c435e62ded3753466779"
PODIO_TOKEN_CHAPTERS = "746b8c51104df9ffcfa204282847b597"
PODIO_TOKEN_TECHNICIANS = "390a81efa05b78ba46cc6204b378e212"
